## This is not the most secure way to store secrets within kubernetes 
## and ideally these would be hosted externally and pulled in or a credential manager be used. 
## However for a local dev setup this will suffice
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/name: {{ .Chart.Name }}
  name: {{ .Chart.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.config.auth.username }}
  password: {{ .Values.config.auth.password }}