apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/name: {{ .Chart.Name }}
  name: {{ .Chart.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.config.auth.username }}
  password: {{ .Values.config.auth.password }}